version: '3.9'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "${DJANGO_PORT_SERV:-8765}:${DJANGO_PORT:-8765}"
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${DJANGO_PORT:-8765}/api/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 20s
