apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-devops-python
  namespace: namespace-devops-python

spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-devops-python
  template:
    metadata:
      labels:
        app: demo-devops-python
    spec:
      containers:
      - name: demo-devops-python
        image: freperush/demo-devops-python:latest
        ports:
        - containerPort: 8765
        env:
        - name: DJANGO_SETTINGS_MODULE
          valueFrom:
            configMapKeyRef:
              name: demo-config
              key: settings
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DJANGO_SECRET_KEY
        - name: DATABASE_NAME
          value: db.sqlite3
        - name: PYTHONUNBUFFERED
          value: "1"