apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-devops-python-ingress
  namespace: namespace-devops-python
  annotations:
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/v1beta1.FrontendConfig: "demo-devops-python-frontendconfig"
spec:
  defaultBackend:
    service:
      name: demo-devops-python-service
      port:
        number: 80
  rules:
  - host: demo-devops-python.local
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: demo-devops-python-service
            port:
              number: 80