apiVersion: v1
kind: Service
metadata:
  name: demo-devops-python-service
  namespace: namespace-devops-python
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    cloud.google.com/backend-config: '{"default":"demo-devops-python-backendconfig"}'
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8765
  selector:
    app: demo-devops-python
  type: ClusterIP